{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: db
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.db.serviceAnnotations }}
  annotations:
{{ toYaml .Values.db.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-db
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 5432
    {{- end }}
  selector:
    app: oes
    component: db
{{- end -}}
