{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
data:
  notification-service-local.yml: | {{- tpl (.Files.Get "config/oes-notification-service/notification-service-local.yml") . |b64enc | nindent 4  }}
kind: Secret
metadata:
  labels:
    app: oes
    component: notificationservice
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-notification-service-config
{{- end -}}
