{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: oes
    component: notificationservice
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: notificationservice
  template:
    metadata:
      annotations:
        configmap/checksum: {{ (.Files.Glob "config/oes-notification-service/notification-service-local.yml").AsConfig | sha256sum }}
{{- if .Values.audit.annotations -}}
        {{ toYaml .Values.audit.annotations | nindent 8 }}
{{- end }}
      labels:
        app: oes
        component: notificationservice

{{ include "oes.standard-labels" . | indent 8 }}
    spec:
      {{- if (eq .Values.db.enabled true) }}
      initContainers:
      - name: db-check
        image: {{ .Values.global.customImages.registry }}/pgchecker:v1
        command:
          - sh
          - -c
          - |
            echo 'Waiting for OES-DB to become ready...'
            until printf "." && nc -z -w 2 oes-db 5432; do
               sleep 2;
            done;
            echo 'OESDB OK ✓'
      {{- end }}
      containers:
      - image: {{ .Values.global.customImages.registry }}/{{ .Values.notificationservice.image.repository }}:{{ .Values.notificationservice.image.tag }}
        imagePullPolicy: IfNotPresent
        name: oes-notification-service
        env:
       {{- if .Values.extraEnvVars }}
       {{- include "tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 8 }}
       {{- end }}
        ports:
        - containerPort: 8099
          name: backend
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /mgmt/health
            port: 8099
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8099
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opsmx/conf/notification-service-local.yml
          name: notification-config-volume
          subPath: notification-service-local.yml
        - mountPath: /opsmx/conf/bootstrap.yml
          name: bootstrap-config-volume
          subPath: bootstrap.yml
        - mountPath: /opsmx/conf/standard-error-code.csv
          name: standard-error-conf
          subPath: standard-error-codes.csv
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      {{- if and (.Values.global.openshift) (not .Values.global.securityContext) }}
      securityContext: {{ default "{}" }}
      {{- else }}
      {{- if and (.Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- else }}
      {{- if and (not .Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.global.customCerts.enabled }}
      - name: cacerts
        secret:
          secretName: {{ .Values.global.customCerts.secretName }}
          items:
          - key: cacerts
            path: cacerts
      {{- end }}
      volumes:
      - name: notification-config-volume
        secret:
          defaultMode: 420
          items:
          - key: notification-service-local.yml
            path: notification-service-local.yml
          secretName: oes-notification-service-config
      - name: bootstrap-config-volume
        secret:
          defaultMode: 420
          secretName: bootstrap
      - configMap:
          defaultMode: 420
          items:
          - key: standard-error-codes.csv
            path: standard-error-codes.csv
          name: standard-error-codes-config
        name: standard-error-conf
{{- end -}}
